/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.24
 * Generated at: 2018-03-05 00:42:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.study;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class board_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/504CLASS%2001/git/ILuvStudy/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ILuvStudy_v1_0/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1519538057135L));
    _jspx_dependants.put("jar:file:/C:/Users/504CLASS%2001/git/ILuvStudy/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ILuvStudy_v1_0/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("    <script src=\"http://code.jquery.com/jquery-1.7.js\"></script>\r\n");
      out.write("    <script src=\"http://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <style>\r\n");
      out.write("    h1 {float:left;}\r\n");
      out.write("    #nav1{float:left; height:40px;}\r\n");
      out.write("    #nav1 > a {text-decoration-line: none;}\r\n");
      out.write("    #nav2{float:right;}    \r\n");
      out.write("    #nav2 > a {text-decoration-line: none;}\r\n");
      out.write("    \r\n");
      out.write("    #header{height: 150px;}\r\n");
      out.write("\r\n");
      out.write("    #brdimg{background-color:pink;}\r\n");
      out.write("    .ctbutton{float:right;}\r\n");
      out.write("\r\n");
      out.write("    .brdtext{float:left; margin-right:8px;}\r\n");
      out.write("\r\n");
      out.write("    #grycontainer{border:2px solid red; height:300px; width:800px;}\r\n");
      out.write("\r\n");
      out.write("    div.gallery {\r\n");
      out.write("    margin: 5px;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    float: left;\r\n");
      out.write("    width: 180px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.gallery:hover {\r\n");
      out.write("    border: 1px solid #777;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.gallery img {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.desc {\r\n");
      out.write("    padding: 15px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("    </style>    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- bno값 유지하자 -->\r\n");
      out.write("<form role=\"form\" method=\"post\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"bno\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${studyVO.bno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("        <header id=\"header\">       \r\n");
      out.write("            <nav id=\"nav1\">\r\n");
      out.write("                <a href=\"listAll.html\">전체</a>\r\n");
      out.write("                <a href=\"boarder.html\">외국어</a>\r\n");
      out.write("                <a href=\"boarder.html\">IT</a>\r\n");
      out.write("                <a href=\"boarder.html\">교양</a>\r\n");
      out.write("                <a href=\"boarder.html\">공무원</a>\r\n");
      out.write("            </nav>\r\n");
      out.write("        \r\n");
      out.write("            <nav id=\"nav2\">\r\n");
      out.write("                <a href=\"profile.html\">마이페이지</a>\r\n");
      out.write("                <a href=\"\">로그아웃</a>\r\n");
      out.write("                <a href=\"register1.html\">스터디등록</a>\r\n");
      out.write("                <a href=\"qna.html\">QNA</a>\r\n");
      out.write("                <a href=\"notice.html\">공지사항</a>\r\n");
      out.write("            </nav>\r\n");
      out.write("        \r\n");
      out.write("        </header>\r\n");
      out.write("\r\n");
      out.write("        <div style=\"height:700px;\">\r\n");
      out.write("            <div id=\"brdimg\">\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                <!-- 스터디 제목 -->\r\n");
      out.write("                <h2>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${studyVO.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2>\r\n");
      out.write("                <!-- 작성자 -->\r\n");
      out.write("                <p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${studyVO.nickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>   <i class=\"fa fa-heart-o\" style=\"font-size:36px;\"></i>\r\n");
      out.write("                \r\n");
      out.write("                <!-- 이건뭐죠 >? -->\r\n");
      out.write("                <select class=\"ctbutton\">\r\n");
      out.write("                    <option>IT</option>\r\n");
      out.write("                    <option>교양</option>\r\n");
      out.write("                    <option>라이프스타일</option>\r\n");
      out.write("                    \r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <table>\r\n");
      out.write("                <tr>\r\n");
      out.write("                <!-- 카테고리 -->\r\n");
      out.write("                    <td>카테고리</td>\r\n");
      out.write("                    <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${studyVO.cDName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(',');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${studyVO.cSName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                <!-- 현재인원 -->\r\n");
      out.write("                    <td>현재인원</td>\r\n");
      out.write("                    <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${studyVO.now}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                <!-- 최대인원 -->\r\n");
      out.write("                    <td>최대인원</td>\r\n");
      out.write("                    <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${studyVO.max}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                <!-- 지역 -->\r\n");
      out.write("                    <td>지역</td>\r\n");
      out.write("                    <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${studyVO.rDName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('/');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${studyVO.rSName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                <!-- 시작날짜 -->\r\n");
      out.write("                    <td>시작날짜</td>\r\n");
      out.write("                    <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${studyVO.sd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                    <!-- 시작시간 -->\r\n");
      out.write("                    <td>시작시간</td>\r\n");
      out.write("                    <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${studyVO.st}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                    <!-- 끝나는시간 -->\r\n");
      out.write("                    <td>끝나는시간</td>\r\n");
      out.write("                    <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${studyVO.et}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            <!-- 요일별 -->\r\n");
      out.write("            <div>요일별 스터디 시간 <p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${studyVO.sc}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p></div>\r\n");
      out.write("            <!-- 스터디내용 -->\r\n");
      out.write("            <div class=\"brdtext\"><p>소개글</p></div>\r\n");
      out.write("            <div class=\"brdtext\"><p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${studyVO.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p></div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <!-- 첨부파일 나중에 합시다 -->\r\n");
      out.write("    <div id=\"grycontainer\">  \r\n");
      out.write("        <div class=\"gallery\">\r\n");
      out.write("     <!--            <a target=\"_blank\" href=\"sohee.jpg\">\r\n");
      out.write("                  <img src=\"sohee.jpg\" alt=\"Trolltunga Norway\" width=\"150\" height=\"200\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <div class=\"desc\">귀요미</div>\r\n");
      out.write("        </div>\r\n");
      out.write("            \r\n");
      out.write("        <div class=\"gallery\">\r\n");
      out.write("                <a target=\"_blank\" href=\"assa.gif\">\r\n");
      out.write("                  <img src=\"assa.gif\" alt=\"Forest\" width=\"600\" height=\"400\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <div class=\"desc\">귀요미</div>\r\n");
      out.write("        </div>\r\n");
      out.write("              \r\n");
      out.write("        <div class=\"gallery\">\r\n");
      out.write("                <a target=\"_blank\" href=\"sh.jpg\">\r\n");
      out.write("                  <img src=\"sh.jpg\" alt=\"Northern Lights\" width=\"600\" height=\"400\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <div class=\"desc\">귀요미</div>\r\n");
      out.write("        </div>\r\n");
      out.write("              \r\n");
      out.write("        <div class=\"gallery\">\r\n");
      out.write("                <a target=\"_blank\" href=\"shh.jpg\">\r\n");
      out.write("                  <img src=\"shh.jpg\" alt=\"Mountains\" width=\"600\" height=\"400\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <div class=\"desc\">귀요미</div>  -->\r\n");
      out.write("        </div>\r\n");
      out.write("    </div><!-- end grycontainer -->\r\n");
      out.write("\r\n");
      out.write("    <div>\r\n");
      out.write("\r\n");
      out.write("        <span>작성자</span>\r\n");
      out.write("        <input type=\"text\" name=\"writer\" id=\"writer\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${studyVO.writer}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("        <span><input type=\"text\" name=\"content\" id=\"content\" value=\"댓글을 입력해 주세요.\"></span>\r\n");
      out.write("        <input type=\"checkbox\" >비밀글 <input type=\"button\" id=\"addBtn\" value=\"댓글작성\"><br>\r\n");
      out.write("        \r\n");
      out.write("                      댓글 테스트\r\n");
      out.write("        <ul id=\"replies\"> </ul>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("    </br></br>\r\n");
      out.write("    \r\n");
      out.write("    \t신청하는 사람\r\n");
      out.write("        <input type=\"submit\" value=\"신청하기\">\r\n");
      out.write("        <input type=\"submit\" class=\"preee\" value=\"목록으로\">\r\n");
      out.write("        <!-- 로그인시 --> </br></br>\r\n");
      out.write("        \r\n");
      out.write("                     등록한 사람   \r\n");
      out.write("        <input type=\"submit\" class=\"preee\" value=\"목록\">\r\n");
      out.write("        <input type=\"submit\" value=\"수정\">\r\n");
      out.write("        <input type=\"submit\" class=\"delete\" value=\"삭제\">\r\n");
      out.write("        <input type=\"submit\" value=\"스터디완료\">\r\n");
      out.write("    </div>\r\n");
      out.write("<!-- <script id=\"template\" type=\"text/x-handlebars-template\">\r\n");
      out.write("{{#each .}}\r\n");
      out.write("<li class=\"replyLi\" data-rno={{rno}}>\r\n");
      out.write("<div class=\"timeline-item\">\r\n");
      out.write("<span class=\"time\">\r\n");
      out.write("{{prettifyDate regdate}}\r\n");
      out.write("</span>\r\n");
      out.write("<h3 class=\"timeline-header\"><strong>{{rno}}</strong> -{{writer}}</h3>\r\n");
      out.write("<div class=\"timeline-body\">{{content}}</div>\r\n");
      out.write("<div class=\"timeline-footer\">\r\n");
      out.write("<a class=\"btn btn-primary btn-xs\" data-toggle=\"modal\" data-target=\"#modifyModal\">Modify</a>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</li>\r\n");
      out.write("{{each}}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("Handlebars.registerHelper(\"prettifyDate\", function(timeValue){\r\n");
      out.write("\tvar dateObj = new Date(timeValue);\r\n");
      out.write("\tvar year = dateObj.getFullYear();\r\n");
      out.write("\tvar month = dateObj.getMonth()+1;\r\n");
      out.write("\tvar date = dateObj.getDate();\r\n");
      out.write("\treturn year+\"/\"+month+\"/\"+date;\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("var printData = function(replyArr, target, templateObject) {\r\n");
      out.write("\t\r\n");
      out.write("\tvar template = Handlebars.compile(templateObject.html());\r\n");
      out.write("\t\r\n");
      out.write("\tvar html = template(replyArr);\r\n");
      out.write("\t$(\".replyLi\").remove();\r\n");
      out.write("\ttarget.after(html);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t\r\n");
      out.write("\tvar formObj = $(\"form[role='form']\");\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".preee\").on(\"click\", function(){\r\n");
      out.write("\t\tself.location = \"/study/listAll?page=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.page}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&perPageNum=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cri.perPageNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".delete\").on(\"click\", function(){\r\n");
      out.write("\t\tformObj.attr(\"action\", \"/study/remove\");\r\n");
      out.write("\t\tformObj.submit();\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".fa fa-heart-o\").on(\"click\", function(){\r\n");
      out.write("\t\t<i class=\"fa fa-heart\" style=\"font-size:36px;\"></i>\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("</script>   \r\n");
      out.write(" \r\n");
      out.write("        <script>\r\n");
      out.write("    \r\n");
      out.write("        var bno = 4934;\r\n");
      out.write("\r\n");
      out.write("        $(\"#addBtn\").on(\"click\", function(){\r\n");
      out.write("        \t\r\n");
      out.write("        \tvar writer = $(\"#writer\").val();\r\n");
      out.write("        \tvar content = $(\"#content\").val();\r\n");
      out.write("        \t\r\n");
      out.write("        \t$.ajax({\r\n");
      out.write("        \t\ttype:\"post\",\r\n");
      out.write("        \t\turl:\"/study/replies/create\",\r\n");
      out.write("        \t\theaders:{\r\n");
      out.write("        \t\t\t\"Content-Type\":\"application/json\",\r\n");
      out.write("        \t\t\t\"X-HTTP-Method-Override\":\"POST\"\r\n");
      out.write("        \t\t},\r\n");
      out.write("        \t\tdataType:\"text\",\r\n");
      out.write("        \t\tdata:JSON.stringify({\r\n");
      out.write("        \t\t\tbsBno:bno,\r\n");
      out.write("        \t\t\twriter:writer,\r\n");
      out.write("        \t\t\tcontent:content\r\n");
      out.write("        \t\t}),\r\n");
      out.write("        \t\tsuccess:function(result){\r\n");
      out.write("        \t\t\tif(result=='success'){\r\n");
      out.write("        \t\t\t\talert(\"등록\");\r\n");
      out.write("        \t\t\t\tgetAllList();\r\n");
      out.write("        \t\t\t}\r\n");
      out.write("        \t\t}\r\n");
      out.write("        \t});\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        function getAllList() {\r\n");
      out.write("            \r\n");
      out.write("            $.getJSON(\"/study/replies/all/\" + bno, function(data){\r\n");
      out.write("            \t\r\n");
      out.write("            \tconsole.log(bno);\r\n");
      out.write("            \t\r\n");
      out.write("            \tvar str=\"\";\r\n");
      out.write("            \tconsole.log(data.length);\r\n");
      out.write("            \t\r\n");
      out.write("            \t$(data).each(\r\n");
      out.write("            \t\t\tfunction(){\r\n");
      out.write("     \t\t\t\t\t\tstr += \"<li data-rno='\"+this.rno+\"' class='replyLi'>\"\r\n");
      out.write("     \t\t\t\t\t\t    + this.rno + \":\" + this.content\r\n");
      out.write("     \t\t\t\t\t\t    + \"</li>\";\r\n");
      out.write("            \t\t\t});\r\n");
      out.write("            \t\r\n");
      out.write("            \t\t$(\"#replies\").html(str);\r\n");
      out.write("            \t});\r\n");
      out.write("           }    \r\n");
      out.write("        </script>    \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/study/board.jsp(83,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${studyVO.name!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<div class='uploadedList'>\r\n");
          out.write("\t\t\t\t\t\t<span class=\"mailbox-attachment-icon has-img\"><img\r\n");
          out.write("\t\t\t\t\t\t\tsrc=\"/study/displayFile?fileName=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${studyVO.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("\t\t\t\t\t\t\talt=\"Attachment\"></span>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
